import { hexToRgb } from '@act-one/design';
import { RIGS, type ThreeDScene } from './rigs.ts';

/**
 * Blender script generation.
 *
 * Every value interpolated below has already passed the ThreeDScene schema, so
 * it is a bounded number, a member of a closed enum, or a storage path that has
 * been separately validated. Nothing here concatenates model output into Python.
 *
 * Paths are the one string that reaches the script, so they are emitted through
 * a JSON encoder rather than quoted by hand — a filename containing a quote or
 * a backslash would otherwise break out of the string literal, and in a
 * language with `os.system` that is not a cosmetic bug.
 */
export function buildBlenderScript(scene: ThreeDScene): string {
  const rig = RIGS[scene.rig];
  const background = linear(scene.backgroundColor);
  const accent = linear(scene.accentColor);

  return `# Generated by Act One. Do not edit.
# Rig: ${rig.name} — ${rig.purpose}
import bpy
import math

SCREENS = ${py(scene.screenAssets)}
DEPTH = ${num(scene.depth)}
DURATION = ${num(scene.durationSeconds)}
FPS = ${int(scene.fps)}
WIDTH = ${int(scene.width)}
HEIGHT = ${int(scene.height)}
FOCAL = ${num(scene.focalLengthMm)}
DOF = ${num(scene.depthOfField)}
SAMPLES = ${int(scene.samples)}
BACKGROUND = (${num(background.r)}, ${num(background.g)}, ${num(background.b)}, 1.0)
ACCENT = (${num(accent.r)}, ${num(accent.g)}, ${num(accent.b)}, 1.0)


def reset():
    bpy.ops.wm.read_factory_settings(use_empty=True)
    scene = bpy.context.scene
    scene.render.engine = 'CYCLES'
    scene.cycles.samples = SAMPLES
    # Denoising lets us run far fewer samples for the same visual result, which
    # is the difference between a viable render budget and an unviable one.
    scene.cycles.use_denoising = True
    scene.render.resolution_x = WIDTH
    scene.render.resolution_y = HEIGHT
    scene.render.resolution_percentage = 100
    scene.render.fps = FPS
    scene.frame_start = 1
    scene.frame_end = max(1, int(round(DURATION * FPS)))
    scene.render.film_transparent = ${scene.background === 'void' ? 'True' : 'False'}
    # EXR sequence, not a video file: the compositor needs the alpha and the
    # full dynamic range, and re-encoding here would throw both away.
    scene.render.image_settings.file_format = 'OPEN_EXR'
    scene.render.image_settings.color_depth = '16'
    return scene


def world(scene):
    bpy.ops.world.new()
    world = bpy.data.worlds[-1]
    scene.world = world
    world.use_nodes = True
    bg = world.node_tree.nodes['Background']
    bg.inputs[0].default_value = BACKGROUND
    bg.inputs[1].default_value = ${scene.background === 'void' ? '0.02' : '0.35'}


def screen_material(name, image_path):
    material = bpy.data.materials.new(name)
    material.use_nodes = True
    nodes = material.node_tree.nodes
    links = material.node_tree.links
    output = nodes['Material Output']
    nodes.remove(nodes['Principled BSDF'])

    # Interface is emissive, not lit. A screen that receives key light picks up
    # a sheen no real display has, and the whole shot stops reading as a screen.
    emission = nodes.new('ShaderNodeEmission')
    emission.inputs[1].default_value = 1.25

    texture = nodes.new('ShaderNodeTexImage')
    texture.image = bpy.data.images.load(image_path)
    texture.interpolation = 'Cubic'
    links.new(texture.outputs['Color'], emission.inputs['Color'])
    links.new(emission.outputs['Emission'], output.inputs['Surface'])
    return material


def add_screen(index, image_path):
    bpy.ops.mesh.primitive_plane_add(size=2)
    plane = bpy.context.active_object
    plane.name = 'screen_%d' % index
    plane.rotation_euler = (math.radians(90), 0, 0)
    # 16:9, which is what every captured interface is.
    plane.scale = (1.6, 1.0, 0.9)
${rigLayout(scene)}
    plane.data.materials.append(screen_material('screen_mat_%d' % index, image_path))
    return plane


def lighting():
${lightingBlock(scene)}


def camera(scene):
    bpy.ops.object.camera_add(location=(0, ${num(-6 - scene.depth)}, 0.6))
    cam = bpy.context.active_object
    cam.data.lens = FOCAL
    cam.rotation_euler = (math.radians(90), 0, 0)
    scene.camera = cam

    if DOF > 0:
        cam.data.dof.use_dof = True
        cam.data.dof.focus_distance = ${num(6 + scene.depth)}
        # Wide open at DOF=1 is f/1.2, which is shallow enough to lose the
        # interface entirely — the cap keeps the product readable.
        cam.data.dof.aperture_fstop = max(1.2, 8.0 - DOF * 6.0)

${cameraBlock(scene)}
    return cam


def main():
    scene = reset()
    world(scene)
    for index, path in enumerate(SCREENS):
        add_screen(index, path)
    lighting()
    camera(scene)


main()
`;
}

/** Per-rig plane placement. Emitted as indented Python inside add_screen. */
function rigLayout(scene: ThreeDScene): string {
  switch (scene.rig) {
    case 'floating_ui':
      return indent(`
offset = (index - (len(SCREENS) - 1) / 2.0)
plane.location = (offset * 2.6, -offset * DEPTH, offset * 0.35)
plane.rotation_euler = (math.radians(90), 0, math.radians(-offset * 11))`);

    case 'screen_tunnel':
      return indent(`
plane.location = (0, index * DEPTH * 2.4, 0)
plane.rotation_euler = (math.radians(90), 0, math.radians((index % 2) * 4 - 2))
plane.scale = (2.4, 1.0, 1.35)`);

    case 'layered_depth':
      return indent(`
plane.location = (index * 0.22, -index * DEPTH, index * 0.18)
plane.rotation_euler = (math.radians(90), 0, math.radians(-8))`);

    case 'card_stack':
      return indent(`
angle = (index - (len(SCREENS) - 1) / 2.0) * 9.0
plane.location = (index * 0.42, -index * DEPTH * 0.55, index * 0.1)
plane.rotation_euler = (math.radians(90), 0, math.radians(angle))
plane.scale = (1.15, 1.0, 1.55)`);

    case 'browser_float':
      return indent(`
plane.location = (0.3, 0, 0.1)
plane.rotation_euler = (math.radians(90), 0, math.radians(-13))`);

    case 'glass_planes':
      return indent(`
plane.location = ((index - 1) * 1.9, -index * DEPTH, 0)
plane.rotation_euler = (math.radians(90), 0, math.radians((index - 1) * -7))`);

    case 'device_laptop':
      return indent(`
plane.location = (0, 0, 0.42)
plane.rotation_euler = (math.radians(78), 0, 0)
plane.scale = (1.6, 1.0, 1.0)`);

    case 'device_phone':
      return indent(`
plane.location = (0, 0, 0)
plane.rotation_euler = (math.radians(90), 0, math.radians(-6))
plane.scale = (0.52, 1.0, 1.12)`);

    case 'spatial_transition':
      return indent(`
offset = (index - (len(SCREENS) - 1) / 2.0)
plane.location = (offset * 3.1, -abs(offset) * DEPTH, offset * 0.2)
plane.rotation_euler = (math.radians(90), 0, math.radians(-offset * 15))`);

    case 'logo_extrusion':
    default:
      return indent(`
plane.location = (0, 0, 0)`);
  }
}

function lightingBlock(scene: ThreeDScene): string {
  const common = `
    bpy.ops.object.light_add(type='AREA', location=(4, -5, 4))
    key = bpy.context.active_object
    key.data.energy = %ENERGY%
    key.data.size = %SIZE%
    key.rotation_euler = (math.radians(52), 0, math.radians(38))
`;

  switch (scene.lighting) {
    case 'single_key':
      return common.replace('%ENERGY%', '700').replace('%SIZE%', '4');

    case 'rim_dark':
      return (
        common.replace('%ENERGY%', '280').replace('%SIZE%', '3') +
        `
    # The rim carries the shape. On a dark canvas it is the only thing
    # separating the object from the background.
    bpy.ops.object.light_add(type='AREA', location=(-5, 4, 2.5))
    rim = bpy.context.active_object
    rim.data.energy = 620
    rim.data.size = 2
    rim.data.color = ACCENT[:3]
    rim.rotation_euler = (math.radians(74), 0, math.radians(-128))
`
      );

    case 'daylight':
      return common.replace('%ENERGY%', '1100').replace('%SIZE%', '9');

    case 'product_table':
      return (
        common.replace('%ENERGY%', '820').replace('%SIZE%', '6') +
        `
    bpy.ops.object.light_add(type='AREA', location=(-3.5, -4, 1.4))
    fill = bpy.context.active_object
    fill.data.energy = 220
    fill.data.size = 5
    fill.rotation_euler = (math.radians(64), 0, math.radians(-42))
`
      );

    case 'studio_soft':
    default:
      return (
        common.replace('%ENERGY%', '520').replace('%SIZE%', '7') +
        `
    bpy.ops.object.light_add(type='AREA', location=(-4, -4.5, 2))
    fill = bpy.context.active_object
    fill.data.energy = 190
    fill.data.size = 6
    fill.rotation_euler = (math.radians(66), 0, math.radians(-40))
`
      );
  }
}

/**
 * Camera animation.
 *
 * Keyframed over the scene's own duration rather than a fixed frame count, so
 * a 2-second and a 6-second version of the same shot move at the same apparent
 * speed instead of one crawling.
 */
function cameraBlock(scene: ThreeDScene): string {
  const end = 'scene.frame_end';

  switch (scene.camera) {
    case 'slow_push':
      return `    cam.location = (0, ${num(-6.6 - scene.depth)}, 0.6)
    cam.keyframe_insert('location', frame=1)
    cam.location = (0, ${num(-5.7 - scene.depth)}, 0.62)
    cam.keyframe_insert('location', frame=${end})
`;
    case 'slow_pull':
      return `    cam.location = (0, ${num(-5.5 - scene.depth)}, 0.6)
    cam.keyframe_insert('location', frame=1)
    cam.location = (0, ${num(-6.9 - scene.depth)}, 0.66)
    cam.keyframe_insert('location', frame=${end})
`;
    case 'orbit_left':
    case 'orbit_right': {
      const sign = scene.camera === 'orbit_left' ? -1 : 1;
      return `    radius = ${num(6.2 + scene.depth)}
    for frame in (1, ${end}):
        t = 0.0 if frame == 1 else 1.0
        angle = math.radians(${num(sign * -7)} + t * ${num(sign * 14)})
        cam.location = (math.sin(angle) * radius, -math.cos(angle) * radius, 0.6)
        cam.rotation_euler = (math.radians(90), 0, angle)
        cam.keyframe_insert('location', frame=frame)
        cam.keyframe_insert('rotation_euler', frame=frame)
`;
    }
    case 'rise':
      return `    cam.location = (0, ${num(-6.2 - scene.depth)}, -0.2)
    cam.keyframe_insert('location', frame=1)
    cam.location = (0, ${num(-6.2 - scene.depth)}, 0.85)
    cam.keyframe_insert('location', frame=${end})
`;
    case 'static':
    default:
      return '    pass\n';
  }
}

function indent(block: string): string {
  return block
    .trim()
    .split('\n')
    .map((line) => `    ${line}`)
    .join('\n');
}

/** JSON-encoded, so a path can never break out of the Python string literal. */
function py(values: string[]): string {
  return `[${values.map((value) => JSON.stringify(value)).join(', ')}]`;
}

function num(value: number): string {
  if (!Number.isFinite(value)) throw new Error('Refusing to emit a non-finite number into a script.');
  return value.toFixed(4);
}

function int(value: number): string {
  if (!Number.isInteger(value)) throw new Error('Refusing to emit a non-integer where an integer is required.');
  return String(value);
}

/** sRGB hex to linear float, which is the space Blender's node inputs expect. */
function linear(hex: string): { r: number; g: number; b: number } {
  const { r, g, b } = hexToRgb(hex);
  const toLinear = (channel: number) => {
    const c = channel / 255;
    return c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4;
  };
  return { r: toLinear(r), g: toLinear(g), b: toLinear(b) };
}
