import { hexToRgb } from '@act-one/design';
import { RIGS, type ThreeDScene } from './rigs.ts';

/**
 * Blender script generation.
 *
 * Every value interpolated below has already passed the ThreeDScene schema, so
 * it is a bounded number, a member of a closed enum, or a storage path that has
 * been separately validated. Nothing here concatenates model output into Python.
 *
 * Paths are the one string that reaches the script, so they are emitted through
 * a JSON encoder rather than quoted by hand — a filename containing a quote or
 * a backslash would otherwise break out of the string literal, and in a
 * language with `os.system` that is not a cosmetic bug.
 */
export function buildBlenderScript(
  scene: ThreeDScene,
  options: { outputPattern?: string } = {},
): string {
  const rig = RIGS[scene.rig];
  const background = linear(scene.backgroundColor);
  const accent = linear(scene.accentColor);
  const surface = liftedSurface(background);

  return `# Generated by Act One. Do not edit.
# Rig: ${rig.name} — ${rig.purpose}
import bpy
import math

SCREENS = ${py(scene.screenAssets)}
DEPTH = ${num(scene.depth)}
DURATION = ${num(scene.durationSeconds)}
FPS = ${int(scene.fps)}
WIDTH = ${int(scene.width)}
HEIGHT = ${int(scene.height)}
FOCAL = ${num(scene.focalLengthMm)}
DOF = ${num(scene.depthOfField)}
SAMPLES = ${int(scene.samples)}
# Where frames go, as "dir/frame_" with the frame number appended. Empty
# builds the scene and renders nothing, which is what the tests want.
OUTPUT = ${JSON.stringify(options.outputPattern ?? '')}
BACKGROUND = (${num(background.r)}, ${num(background.g)}, ${num(background.b)}, 1.0)
ACCENT = (${num(accent.r)}, ${num(accent.g)}, ${num(accent.b)}, 1.0)
# The form's own surface: the canvas lifted off black, so the object separates
# from the void without becoming a light source.
SURFACE = (${num(surface.r)}, ${num(surface.g)}, ${num(surface.b)}, 1.0)
ROUGHNESS = ${num(roughnessFor(scene))}
METALLIC = ${num(metallicFor(scene))}
# Whether this rig builds its own geometry rather than staging a capture.
FORM = ${isForm(scene) ? 'True' : 'False'}


def reset():
    bpy.ops.wm.read_factory_settings(use_empty=True)
    scene = bpy.context.scene
    scene.render.engine = 'CYCLES'
    scene.cycles.samples = SAMPLES
    # Denoising lets us run far fewer samples for the same visual result, which
    # is the difference between a viable render budget and an unviable one.
    # A build without OpenImageDenoise lists no denoisers at all; asking for
    # one there fails before a frame is rendered. Without it, samples go up
    # to buy the same quality.
    denoisers = [item.identifier for item in scene.cycles.bl_rna.properties['denoiser'].enum_items]
    if 'OPENIMAGEDENOISE' in denoisers:
        scene.cycles.denoiser = 'OPENIMAGEDENOISE'
        scene.cycles.use_denoising = True
    else:
        scene.cycles.use_denoising = False
        scene.cycles.samples = min(512, SAMPLES * 3)
    scene.render.resolution_x = WIDTH
    scene.render.resolution_y = HEIGHT
    scene.render.resolution_percentage = 100
    scene.render.fps = FPS
    scene.frame_start = 1
    scene.frame_end = max(1, int(round(DURATION * FPS)))
    scene.render.film_transparent = ${scene.background === 'void' ? 'True' : 'False'}
    # EXR sequence, not a video file: the compositor needs the alpha and the
    # full dynamic range, and re-encoding here would throw both away.
    scene.render.image_settings.file_format = 'OPEN_EXR'
    scene.render.image_settings.color_depth = '16'
    return scene


def world(scene):
    bpy.ops.world.new()
    world = bpy.data.worlds[-1]
    scene.world = world
    world.use_nodes = True
    bg = world.node_tree.nodes['Background']
    bg.inputs[0].default_value = BACKGROUND
    bg.inputs[1].default_value = ${scene.background === 'void' ? '0.02' : '0.35'}


def screen_material(name, image_path):
    material = bpy.data.materials.new(name)
    material.use_nodes = True
    nodes = material.node_tree.nodes
    links = material.node_tree.links
    output = nodes['Material Output']
    nodes.remove(nodes['Principled BSDF'])

    # Interface is emissive, not lit. A screen that receives key light picks up
    # a sheen no real display has, and the whole shot stops reading as a screen.
    emission = nodes.new('ShaderNodeEmission')
    emission.inputs[1].default_value = 1.25

    texture = nodes.new('ShaderNodeTexImage')
    texture.image = bpy.data.images.load(image_path)
    texture.interpolation = 'Cubic'
    links.new(texture.outputs['Color'], emission.inputs['Color'])
    links.new(emission.outputs['Emission'], output.inputs['Surface'])
    return material


def form_material(name):
    """A real surface: a dielectric with a little metal, and a roughness that
    varies across it.

    The varying roughness is the whole thing. A uniform surface is what makes a
    render read as a render — real material is never equally polished
    everywhere, and the eye knows it before it can say why. One noise texture
    into roughness is the cheapest possible version of that and it is the
    difference between an object and a grey box.

    Deliberately not emissive. An emissive form is a glow, and a glow is the
    look this whole system exists to avoid; a surface that has to be lit is
    what makes the light in the shot look like light.
    """
    material = bpy.data.materials.new(name)
    material.use_nodes = True
    nodes = material.node_tree.nodes
    links = material.node_tree.links
    shader = nodes['Principled BSDF']
    shader.inputs['Base Color'].default_value = SURFACE
    for field, value in (('Metallic', METALLIC), ('IOR', 1.45)):
        if field in shader.inputs:
            shader.inputs[field].default_value = value

    noise = nodes.new('ShaderNodeTexNoise')
    noise.inputs['Scale'].default_value = 5.5
    noise.inputs['Detail'].default_value = 8.0
    noise.inputs['Roughness'].default_value = 0.6
    spread = nodes.new('ShaderNodeMapRange')
    spread.inputs['From Min'].default_value = 0.32
    spread.inputs['From Max'].default_value = 0.68
    spread.inputs['To Min'].default_value = max(0.05, ROUGHNESS - 0.16)
    spread.inputs['To Max'].default_value = min(1.0, ROUGHNESS + 0.16)
    links.new(noise.outputs['Fac'], spread.inputs['Value'])
    links.new(spread.outputs['Result'], shader.inputs['Roughness'])
    return material


def solid(obj, width=0.12, segments=8):
    """Gives a form an edge that catches light, and a surface.

    A hard edge is a single pixel of specular and reads as a render. A wide
    bevel, shaded smooth, turns that edge into a travelling highlight — which
    is what the eye reads as a real object photographed under a real light.
    """
    modifier = obj.modifiers.new('bevel', 'BEVEL')
    modifier.width = width
    modifier.segments = segments
    modifier.limit_method = 'ANGLE'
    modifier.angle_limit = math.radians(30)
    if hasattr(modifier, 'harden_normals'):
        modifier.harden_normals = True
    for polygon in obj.data.polygons:
        polygon.use_smooth = True
    # Flat where the face is flat, smooth around the bevel. Without this the
    # whole form shades as one curve and stops reading as a solid.
    if hasattr(obj.data, 'use_auto_smooth'):
        obj.data.use_auto_smooth = True
        obj.data.auto_smooth_angle = math.radians(38)
    else:
        try:
            bpy.context.view_layer.objects.active = obj
            bpy.ops.object.shade_auto_smooth(angle=math.radians(38))
        except Exception:
            pass
    obj.data.materials.append(form_material('form_%s' % obj.name))
    return obj


def form():
    """Geometry for a shot that holds no interface."""
${formBlock(scene)}


def add_screen(index, image_path):
    bpy.ops.mesh.primitive_plane_add(size=2)
    plane = bpy.context.active_object
    plane.name = 'screen_%d' % index
    plane.rotation_euler = (math.radians(90), 0, 0)
    # 16:9, which is what every captured interface is.
    plane.scale = (1.6, 1.0, 0.9)
${rigLayout(scene)}
    plane.data.materials.append(screen_material('screen_mat_%d' % index, image_path))
    return plane


def lighting():
${lightingBlock(scene)}


def camera(scene):
    bpy.ops.object.camera_add(location=(0, ${num(-6 - scene.depth)}, 0.6))
    cam = bpy.context.active_object
    cam.data.lens = FOCAL
    cam.rotation_euler = (math.radians(90), 0, 0)
    scene.camera = cam

    if DOF > 0:
        cam.data.dof.use_dof = True
        cam.data.dof.focus_distance = ${num(6 + scene.depth)}
        # Wide open at DOF=1 is f/1.2, which is shallow enough to lose the
        # interface entirely — the cap keeps the product readable.
        #
        # A form has no interface to keep readable, and the whole reason it is
        # rendered rather than drawn is the lens: the near edge sharp and
        # everything behind it falling away is what a camera does and a
        # compositor cannot fake. So it opens up properly.
        cam.data.dof.aperture_fstop = max(${isForm(scene) ? '1.2, 3.2' : '1.2, 8.0'} - DOF * ${isForm(scene) ? '2.0' : '6.0'})

${cameraBlock(scene)}
    return cam


def render(scene):
    # The script renders rather than the command line, so a failure can be
    # answered. Not every build has the denoiser — a distribution's Blender
    # may be built without OpenImageDenoise, and asking for it fails at the
    # first frame with "No device available to denoise on". Without it,
    # samples go up to buy the same quality, and the render goes again.
    scene.render.filepath = OUTPUT
    try:
        bpy.ops.render.render(animation=True)
    except Exception as error:
        if 'denois' not in str(error).lower():
            raise
        scene.cycles.use_denoising = False
        scene.cycles.samples = min(512, SAMPLES * 3)
        bpy.ops.render.render(animation=True)


def main():
    scene = reset()
    world(scene)
    for index, path in enumerate(SCREENS):
        add_screen(index, path)
    if FORM and not SCREENS:
        # Nothing to stage. Build the form instead of rendering an empty void,
        # which is what this did for every screenless scene ever planned.
        #
        # Only the form rigs. A logo reveal with no capture is *supposed* to be
        # a void — the motion engine draws the mark over it, and geometry here
        # would be a second object arguing with the lockup.
        form()
    lighting()
    camera(scene)
    if OUTPUT:
        render(scene)


main()
`;
}

/** Per-rig plane placement. Emitted as indented Python inside add_screen. */
function rigLayout(scene: ThreeDScene): string {
  switch (scene.rig) {
    case 'floating_ui':
      return indent(`
offset = (index - (len(SCREENS) - 1) / 2.0)
plane.location = (offset * 2.6, -offset * DEPTH, offset * 0.35)
plane.rotation_euler = (math.radians(90), 0, math.radians(-offset * 11))`);

    case 'screen_tunnel':
      return indent(`
plane.location = (0, index * DEPTH * 2.4, 0)
plane.rotation_euler = (math.radians(90), 0, math.radians((index % 2) * 4 - 2))
plane.scale = (2.4, 1.0, 1.35)`);

    case 'layered_depth':
      return indent(`
plane.location = (index * 0.22, -index * DEPTH, index * 0.18)
plane.rotation_euler = (math.radians(90), 0, math.radians(-8))`);

    case 'card_stack':
      return indent(`
angle = (index - (len(SCREENS) - 1) / 2.0) * 9.0
plane.location = (index * 0.42, -index * DEPTH * 0.55, index * 0.1)
plane.rotation_euler = (math.radians(90), 0, math.radians(angle))
plane.scale = (1.15, 1.0, 1.55)`);

    case 'browser_float':
      return indent(`
plane.location = (0.3, 0, 0.1)
plane.rotation_euler = (math.radians(90), 0, math.radians(-13))`);

    case 'glass_planes':
      return indent(`
plane.location = ((index - 1) * 1.9, -index * DEPTH, 0)
plane.rotation_euler = (math.radians(90), 0, math.radians((index - 1) * -7))`);

    case 'device_laptop':
      return indent(`
plane.location = (0, 0, 0.42)
plane.rotation_euler = (math.radians(78), 0, 0)
plane.scale = (1.6, 1.0, 1.0)`);

    case 'device_phone':
      return indent(`
plane.location = (0, 0, 0)
plane.rotation_euler = (math.radians(90), 0, math.radians(-6))
plane.scale = (0.52, 1.0, 1.12)`);

    case 'spatial_transition':
      return indent(`
offset = (index - (len(SCREENS) - 1) / 2.0)
plane.location = (offset * 3.1, -abs(offset) * DEPTH, offset * 0.2)
plane.rotation_euler = (math.radians(90), 0, math.radians(-offset * 15))`);

    case 'logo_extrusion':
    default:
      return indent(`
plane.location = (0, 0, 0)`);
  }
}

/** Whether this rig builds form from the brand rather than staging a capture. */
function isForm(scene: ThreeDScene): boolean {
  return scene.rig === 'material_monolith' || scene.rig === 'material_field';
}

function lightingBlock(scene: ThreeDScene): string {
  /*
   * A form is lit like an object; a screen is lit around one.
   *
   * The screen rigs keep the light they have always had: modest, off to one
   * side, staying out of the way of an emissive interface. A form has nothing
   * emissive in it, so the light *is* the shot — a big soft key close in for
   * falloff across the surface, a hard accent grazing the back edge to draw
   * the silhouette, and a low fill so the shadow side is dark rather than
   * black. Small lights far away give the flat, even, shadowless look that
   * reads immediately as a default render.
   */
  if (isForm(scene)) {
    return `
    bpy.ops.object.light_add(type='AREA', location=(3.4, -3.2, 3.6))
    key = bpy.context.active_object
    key.data.energy = 900
    # Large and close: the falloff across the face is what gives a flat
    # surface its shape.
    key.data.size = 7
    key.rotation_euler = (math.radians(46), 0, math.radians(42))

    # Grazing the back edge from behind, so it wraps the bevel rather than
    # lighting a face. This is the line that separates the form from the void.
    bpy.ops.object.light_add(type='AREA', location=(-3.6, 3.4, 1.9))
    rim = bpy.context.active_object
    rim.data.energy = 1400
    rim.data.size = 1.2
    rim.data.color = ACCENT[:3]
    rim.rotation_euler = (math.radians(82), 0, math.radians(-133))

    # Just enough to keep the shadow side readable. Without it the unlit half
    # is pure black and the object reads as a cut-out.
    bpy.ops.object.light_add(type='AREA', location=(-2.6, -4.2, -1.2))
    fill = bpy.context.active_object
    fill.data.energy = 120
    fill.data.size = 9
    fill.rotation_euler = (math.radians(108), 0, math.radians(-28))
`;
  }

  const common = `
    bpy.ops.object.light_add(type='AREA', location=(4, -5, 4))
    key = bpy.context.active_object
    key.data.energy = %ENERGY%
    key.data.size = %SIZE%
    key.rotation_euler = (math.radians(52), 0, math.radians(38))
`;

  switch (scene.lighting) {
    case 'single_key':
      return common.replace('%ENERGY%', '700').replace('%SIZE%', '4');

    case 'rim_dark':
      return (
        common.replace('%ENERGY%', '280').replace('%SIZE%', '3') +
        `
    # The rim carries the shape. On a dark canvas it is the only thing
    # separating the object from the background.
    bpy.ops.object.light_add(type='AREA', location=(-5, 4, 2.5))
    rim = bpy.context.active_object
    rim.data.energy = 620
    rim.data.size = 2
    rim.data.color = ACCENT[:3]
    rim.rotation_euler = (math.radians(74), 0, math.radians(-128))
`
      );

    case 'daylight':
      return common.replace('%ENERGY%', '1100').replace('%SIZE%', '9');

    case 'product_table':
      return (
        common.replace('%ENERGY%', '820').replace('%SIZE%', '6') +
        `
    bpy.ops.object.light_add(type='AREA', location=(-3.5, -4, 1.4))
    fill = bpy.context.active_object
    fill.data.energy = 220
    fill.data.size = 5
    fill.rotation_euler = (math.radians(64), 0, math.radians(-42))
`
      );

    case 'studio_soft':
    default:
      return (
        common.replace('%ENERGY%', '520').replace('%SIZE%', '7') +
        `
    bpy.ops.object.light_add(type='AREA', location=(-4, -4.5, 2))
    fill = bpy.context.active_object
    fill.data.energy = 190
    fill.data.size = 6
    fill.rotation_euler = (math.radians(66), 0, math.radians(-40))
`
      );
  }
}

/**
 * Camera animation.
 *
 * Keyframed over the scene's own duration rather than a fixed frame count, so
 * a 2-second and a 6-second version of the same shot move at the same apparent
 * speed instead of one crawling.
 */
function cameraBlock(scene: ThreeDScene): string {
  const end = 'scene.frame_end';

  switch (scene.camera) {
    case 'slow_push':
      return `    cam.location = (0, ${num(-6.6 - scene.depth)}, 0.6)
    cam.keyframe_insert('location', frame=1)
    cam.location = (0, ${num(-5.7 - scene.depth)}, 0.62)
    cam.keyframe_insert('location', frame=${end})
`;
    case 'slow_pull':
      return `    cam.location = (0, ${num(-5.5 - scene.depth)}, 0.6)
    cam.keyframe_insert('location', frame=1)
    cam.location = (0, ${num(-6.9 - scene.depth)}, 0.66)
    cam.keyframe_insert('location', frame=${end})
`;
    case 'orbit_left':
    case 'orbit_right': {
      const sign = scene.camera === 'orbit_left' ? -1 : 1;
      return `    radius = ${num(6.2 + scene.depth)}
    for frame in (1, ${end}):
        t = 0.0 if frame == 1 else 1.0
        angle = math.radians(${num(sign * -7)} + t * ${num(sign * 14)})
        cam.location = (math.sin(angle) * radius, -math.cos(angle) * radius, 0.6)
        cam.rotation_euler = (math.radians(90), 0, angle)
        cam.keyframe_insert('location', frame=frame)
        cam.keyframe_insert('rotation_euler', frame=frame)
`;
    }
    case 'rise':
      return `    cam.location = (0, ${num(-6.2 - scene.depth)}, -0.2)
    cam.keyframe_insert('location', frame=1)
    cam.location = (0, ${num(-6.2 - scene.depth)}, 0.85)
    cam.keyframe_insert('location', frame=${end})
`;
    case 'static':
    default:
      return '    pass\n';
  }
}

function indent(block: string): string {
  return block
    .trim()
    .split('\n')
    .map((line) => `    ${line}`)
    .join('\n');
}

/** JSON-encoded, so a path can never break out of the Python string literal. */
function py(values: string[]): string {
  return `[${values.map((value) => JSON.stringify(value)).join(', ')}]`;
}

function num(value: number): string {
  if (!Number.isFinite(value)) throw new Error('Refusing to emit a non-finite number into a script.');
  return value.toFixed(4);
}

function int(value: number): string {
  if (!Number.isInteger(value)) throw new Error('Refusing to emit a non-integer where an integer is required.');
  return String(value);
}

/** sRGB hex to linear float, which is the space Blender's node inputs expect. */
function linear(hex: string): { r: number; g: number; b: number } {
  const { r, g, b } = hexToRgb(hex);
  const toLinear = (channel: number) => {
    const c = channel / 255;
    return c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4;
  };
  return { r: toLinear(r), g: toLinear(g), b: toLinear(b) };
}

/**
 * The surface a screenless form is made of.
 *
 * The brand's own canvas, lifted far enough off black to catch a key light and
 * no further. Lifting it further makes a grey object on a dark field, which
 * reads as a default material; lifting it less makes a silhouette.
 */
function liftedSurface(background: { r: number; g: number; b: number }): {
  r: number;
  g: number;
  b: number;
} {
  const lift = (channel: number) => Math.min(1, channel * 0.55 + 0.06);
  return { r: lift(background.r), g: lift(background.g), b: lift(background.b) };
}

/**
 * How the form takes light.
 *
 * Tied to the scene's own depth of field rather than invented: a shot already
 * isolating one plane wants a surface that holds a highlight, and a shot with
 * everything sharp wants one that does not throw specular into the lens.
 */
function roughnessFor(scene: ThreeDScene): number {
  return round4(0.42 - scene.depthOfField * 0.22);
}

function metallicFor(scene: ThreeDScene): number {
  // Enough for the rim to travel along an edge; not enough to become chrome,
  // which is the single fastest way to make a render look like a render.
  return scene.lighting === 'rim_dark' ? 0.45 : 0.25;
}

/**
 * The geometry for a shot that holds no interface, per rig.
 *
 * Bounded arithmetic over the scene's own validated numbers — no model output
 * reaches this, and every rig is a fixed arrangement rather than a parameter
 * somebody could widen into arbitrary Python.
 */
function formBlock(scene: ThreeDScene): string {
  if (scene.rig === 'material_field') {
    return indent(`
span = 5
for x in range(span):
    for y in range(span):
        bpy.ops.mesh.primitive_cube_add(size=1)
        column = bpy.context.active_object
        column.name = 'form_%d_%d' % (x, y)
        # A smooth two-dimensional wave, so the field reads as landscape
        # rather than as a bar chart of something.
        wave = math.sin((x + 1) * 1.07) * math.cos((y + 1) * 0.83)
        height = 0.45 + 1.15 * (0.5 + 0.5 * wave)
        column.scale = (0.34, 0.34, height)
        column.location = (
            (x - (span - 1) / 2.0) * 1.12,
            (y - (span - 1) / 2.0) * 1.12 * DEPTH,
            height / 2.0 - 0.55,
        )
        solid(column, 0.035, 5)`);
  }

  /*
   * Three forms at three depths, no two the same proportion.
   *
   * Two identical boxes is a render of two boxes. Three elements at different
   * distances give the lens something to do — the near one sharp, the far ones
   * falling away — which is most of what separates a photograph of an object
   * from a picture of a shape.
   */
  return indent(`
bpy.ops.mesh.primitive_cube_add(size=2)
hero = bpy.context.active_object
hero.name = 'monolith'
# Tall enough to run out of the top of the frame, which is what gives it
# scale; a form that fits comfortably inside reads as an icon.
hero.scale = (0.4, 0.4, 1.38)
hero.location = (0.34, 0, 0.62)
hero.rotation_euler = (0, 0, math.radians(24))
solid(hero, 0.1, 8)

bpy.ops.mesh.primitive_cube_add(size=2)
mid = bpy.context.active_object
mid.name = 'monolith_mid'
# Wider and shorter, so the two do not rhyme.
mid.scale = (0.62, 0.22, 0.52)
mid.location = (-1.28, DEPTH * 1.1, -0.34)
mid.rotation_euler = (0, 0, math.radians(-11))
solid(mid, 0.07, 6)

bpy.ops.mesh.primitive_cube_add(size=2)
far = bpy.context.active_object
far.name = 'monolith_far'
far.scale = (0.26, 0.26, 1.02)
far.location = (1.72, DEPTH * 2.6, 0.24)
far.rotation_euler = (0, 0, math.radians(-31))
solid(far, 0.07, 6)`);
}

function round4(value: number): number {
  return Math.round(value * 10000) / 10000;
}
