import { describe, it, expect } from 'vitest';
import { existsSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { DEFAULT_LIBRARY } from '../library.ts';

/**
 * The library's pre-roll claims, against the actual audio.
 *
 * `preRoll` says how long a sample plays before its transient, and the sound
 * director subtracts it when placing a cue — so a sample claiming 80ms of air
 * it does not have is started 80ms early and heard 80ms early. The defect is
 * invisible from the inside: every timeline in the system reports the cue
 * exactly where it was asked for, and only a measurement of the finished
 * master disagrees. Ten of the twelve numbers were wrong when this was first
 * measured, one of them by 200ms.
 *
 * Skipped when the library has not been built, because the samples are
 * generated by `npm run sound-library` rather than committed, and a test that
 * fails on a fresh checkout teaches people to ignore it.
 */
const STORAGE = process.env['ACT_ONE_STORAGE_DIR'] ?? path.resolve('.act-one-demo/storage');

/** A tenth of the file's own peak: past the noise floor, before the summit. */
const THRESHOLD = 0.1;

/** One frame at 30fps. Tighter than that is not audible; looser is a defect. */
const TOLERANCE_SECONDS = 1 / 30;

/**
 * Sounds whose `preRoll` is a design decision rather than a measurement.
 *
 * A riser has no transient to align: its job is to arrive, so its cue time is
 * when it begins and the swell leads into whatever follows. The air texture is
 * a bed and never lands on anything.
 */
const NO_TRANSIENT = /riser|texture/;

async function attackSeconds(file: string): Promise<number | null> {
  const bytes = await readFile(file);
  // Minimal WAV reader: enough for the library's own 16-bit PCM files, and a
  // decoder dependency for one number would be its own kind of mistake.
  if (bytes.toString('ascii', 0, 4) !== 'RIFF') return null;

  let offset = 12;
  let rate = 0;
  let channels = 1;
  let bits = 16;
  while (offset + 8 <= bytes.length) {
    const id = bytes.toString('ascii', offset, offset + 4);
    const size = bytes.readUInt32LE(offset + 4);
    if (id === 'fmt ') {
      channels = bytes.readUInt16LE(offset + 10);
      rate = bytes.readUInt32LE(offset + 12);
      bits = bytes.readUInt16LE(offset + 22);
    } else if (id === 'data') {
      if (bits !== 16 || rate === 0) return null;
      const start = offset + 8;
      const end = Math.min(bytes.length, start + size);
      let peak = 0;
      for (let i = start; i + 1 < end; i += 2 * channels) {
        peak = Math.max(peak, Math.abs(bytes.readInt16LE(i)));
      }
      if (peak === 0) return null;
      const limit = peak * THRESHOLD;
      for (let i = start; i + 1 < end; i += 2 * channels) {
        if (Math.abs(bytes.readInt16LE(i)) >= limit) return (i - start) / (2 * channels) / rate;
      }
      return null;
    }
    offset += 8 + size + (size % 2);
  }
  return null;
}

const built = DEFAULT_LIBRARY.sfx.every((item) => existsSync(path.join(STORAGE, item.storageKey)));

describe.skipIf(!built)('the sound library', () => {
  it('records the pre-roll each sample actually has', async () => {
    const wrong: string[] = [];

    for (const sample of DEFAULT_LIBRARY.sfx) {
      if (NO_TRANSIENT.test(sample.kind)) continue;
      const measured = await attackSeconds(path.join(STORAGE, sample.storageKey));
      if (measured === null) continue;
      const drift = measured - sample.preRoll;
      if (Math.abs(drift) > TOLERANCE_SECONDS) {
        wrong.push(
          `${sample.storageKey}: claims ${(sample.preRoll * 1000).toFixed(0)}ms, ` +
            `attack is at ${(measured * 1000).toFixed(0)}ms (${(drift * 1000).toFixed(0)}ms out)`,
        );
      }
    }

    expect(wrong).toEqual([]);
  }, 60_000);
});
