import { describe, it, expect } from 'vitest';
import { readFile, readdir } from 'node:fs/promises';
import path from 'node:path';

/**
 * The words the product is allowed to say, enforced rather than audited.
 *
 * A microcopy pass is worth exactly as long as it takes somebody to add one
 * more sentence. These rules are the ones that were actually broken before —
 * a provider's name on a customer's screen, "project" where the product says
 * production, "library" after the archive was named — so they are checked on
 * every run instead of re-read by eye every few months.
 *
 * The console is deliberately exempt. Staff surfaces are technical on purpose:
 * they name providers, models, queues and raw errors, and softening them would
 * make the platform harder to operate for nobody's benefit.
 */
const CUSTOMER_SURFACES = [
  'src/app/app',
  'src/app/collections',
  'src/app/blog',
  'src/app/how-it-works',
  'src/app/work',
  'src/app/pricing',
  'src/app/auth',
  'src/app/request-access',
  'src/app/invite',
  'src/components',
];

const ROOT = path.resolve(import.meta.dirname, '..', '..');

async function customerFiles(): Promise<string[]> {
  const found: string[] = [];
  const walk = async (dir: string) => {
    for (const entry of await readdir(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) await walk(full);
      else if (entry.name.endsWith('.tsx') && !entry.name.includes('.test.')) found.push(full);
    }
  };
  for (const surface of CUSTOMER_SURFACES) await walk(path.join(ROOT, surface));
  found.push(path.join(ROOT, 'src/app/page.tsx'), path.join(ROOT, 'src/app/not-found.tsx'));
  return found;
}

/**
 * The sentences in a file, as close as a regular expression gets.
 *
 * JSX text between tags, and string literals that read like prose: a space, a
 * letter, and none of the punctuation that means it is a path, a class name or
 * a key. Comments are stripped first — this is about what the product says,
 * not what the code says about itself.
 */
function prose(source: string): string[] {
  const code = source.replace(/\/\*[\s\S]*?\*\//g, '').replace(/^\s*\/\/.*$/gm, '');
  const out: string[] = [];
  for (const match of code.matchAll(/>([^<>{}]{4,})</g)) {
    // `=>` ... `<` catches whole statements. Prose does not have semicolons,
    // brackets or assignments in it.
    if (/[;=()[\]]/.test(match[1]!)) continue;
    out.push(match[1]!);
  }
  for (const match of code.matchAll(/'([^'\\\n]{6,})'|"([^"\\\n]{6,})"/g)) {
    const text = match[1] ?? match[2] ?? '';
    if (!/\s/.test(text)) continue;
    if (/[/_{}<>@$]|\.\w{2,4}$|^\w+-\w+$/.test(text)) continue;
    out.push(text);
  }
  return out.map((line) => line.replace(/\s+/g, ' ').trim()).filter((line) => /[a-z]{3}/.test(line));
}

const RULES: { name: string; pattern: RegExp }[] = [
  {
    name: 'names a provider, a model or a piece of our machinery',
    pattern: /\b(openai|browserbase|higgsfield|elevenlabs|stripe|supabase|ffmpeg|remotion|blender|postgres|webhook)\b/i,
  },
  {
    name: 'calls the work AI-generated',
    pattern: /\bai[- ]generated\b|\bgenerated by ai\b|\bartificial intelligence\b/i,
  },
  { name: 'says project where the product says production', pattern: /\bprojects?\b/i },
  { name: 'says library where the product says archive', pattern: /\blibrary\b/i },
];

describe('what the product says', () => {
  it('keeps every rule on every customer-facing page', async () => {
    const offences: string[] = [];
    for (const file of await customerFiles()) {
      const source = await readFile(file, 'utf8');
      const where = path.relative(ROOT, file);
      for (const line of prose(source)) {
        for (const rule of RULES) {
          if (rule.pattern.test(line)) offences.push(`${where}: ${rule.name} — "${line.slice(0, 90)}"`);
        }
      }
    }
    expect(offences).toEqual([]);
  });

  it('is looking at something', async () => {
    // A rule that matches nothing because the extractor broke is worse than no
    // rule at all: it passes forever and protects nothing.
    const files = await customerFiles();
    expect(files.length).toBeGreaterThan(30);
    const sample = prose(await readFile(files.find((file) => file.endsWith('not-found.tsx'))!, 'utf8'));
    expect(sample.join(' ')).toMatch(/that page is not here/i);
  });
});
